name: Render Remotion Video

on:
  workflow_dispatch:   # run manually from GitHub UI
  push:
    branches:
      - main           # or whatever branch you want

jobs:
  render-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Render Remotion video
        run: npm run render

      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: remotion-video
          path: out/video.mp4
