
name: Headless Motion Canvas Render

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 3. Install dependencies (handle peer deps)
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    # 4. Run headless render via render.js
    - name: Render Motion Canvas Project
      run: node render.js

    # 5. Upload output video as artifact
    - name: Upload rendered video
      uses: actions/upload-artifact@v4
      with:
        name: rendered-video
        path: out.mp4
