
name: Render Motion Canvas

on:
  push:
    branches:
      - main

jobs:
  render-video:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Render Amazon video
        run: npm run render

      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: amazon-video
          path: output/amazon.mp4
