
name: Render Remotion Video

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - run: npm install --legacy-peer-deps

      # 4️⃣ Render video with correct composition ID
      - run: npx remotion render src/index.tsx AmazonFailure out/video.mp4 --codec=h264

      # 5️⃣ Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: remotion-video
          path: out/video.mp4
