
name: Render Remotion Video

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies with legacy-peer-deps to fix React version conflicts
      - run: npm install --legacy-peer-deps

      # Render your video
      - run: npx remotion render src/Video.tsx out/video.mp4 --codec=h264

      # Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: remotion-video
          path: out/video.mp4
