
name: Render Remotion Video

on:
  workflow_dispatch: # lets you trigger manually
  push:
    branches:
      - main  # or whichever branch you want

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Remotion works well with 18+

      - name: Install dependencies
        run: npm install

      - name: Render Remotion video
        run: |
          npx remotion render src/Video.tsx out/video.mp4 --codec=h264 --crf=18 --concurrency=4

      - name: Upload rendered video
        uses: actions/upload-artifact@v4
        with:
          name: remotion-video
          path: out/video.mp4
